default_hatena: &default_hatena
  hatena_consumer_key: JW9Q8U4vAqHVcQ==
  hatena_consumer_secret: +7p5dTqY6owpgeh7AIDg8p6bnrc=

development:
  secret_key_base: 2ca98041ce6f0c656d2480b349fd6aa3b1e4e06b9ce8b0c9bf4d54f35c3361891db89701e6d624a904df6ba565c687c21bf7838a1487557d167e22916b149a6d
  <<: *default_hatena
  
test:
  secret_key_base: 4c298066dcc1064ad027daa271a85232714e45d3072b43e26dc1aa22cee981bc5947a6a0fe1abfc89bc07a13f1c8d7a81f53caadaaee68c68c85b5868d4a1bad
  <<: *default_hatena
  
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  hatena_consumer_key: <%= ENV["HATENA_CONSUMER_KEY"] %>
  hatena_consumer_secret: <%= ENV["HATENA_CONSUMER_SECRET"] %>
  
