# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ca98041ce6f0c656d2480b349fd6aa3b1e4e06b9ce8b0c9bf4d54f35c3361891db89701e6d624a904df6ba565c687c21bf7838a1487557d167e22916b149a6d

test:
  secret_key_base: 4c298066dcc1064ad027daa271a85232714e45d3072b43e26dc1aa22cee981bc5947a6a0fe1abfc89bc07a13f1c8d7a81f53caadaaee68c68c85b5868d4a1bad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
